apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::116981771137:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-U7RcZSgtpAyG
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-trainee
      userarn: arn:aws:iam::116981771137:user/veera
      username: veera
    - groups:
      - expense-admin
      userarn: arn:aws:iam::116981771137:user/veera
      username: veera
kind: ConfigMap
metadata:
  creationTimestamp: "2025-07-30T15:44:24Z"
  name: aws-auth
  namespace: kube-system
  uid: 077cf61c-c793-485a-bc02-f8f0d9ef8885